apiVersion: fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-app
  namespace: flux-system
spec:
  interval: 10m
  path: "./deployments"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
